--EX1
SELECT NAME FROM CITY
WHERE POPULATION > 120000 AND COUNTRYCODE ="USA"

--EX2
SELECT * FROM CITY
WHERE COUNTRYCODE= "JPN"

--EX3
SELECT CITY, STATE FROM STATION 
WHERE LAT_N IS NOT NULL AND LONG_W IS NOT NULL
  
-- EX4
SELECT DISTINCT CITY FROM STATION
WHERE CITY LIKE 'A%' 
OR CITY LIKE 'E%' 
OR CITY LIKE 'I%' 
OR CITY LIKE 'O%' 
OR CITY LIKE 'U%'

--EX5
SELECT DISTINCT CITY FROM STATION
WHERE (CITY LIKE '%A' 
OR CITY LIKE '%E' 
OR CITY LIKE '%I' 
OR CITY LIKE '%O' 
OR CITY LIKE '%U')
AND LAT_N IS NOT NULL AND LONG_W IS NOT NULL 

--EX6
SELECT DISTINCT city 
FROM station 
WHERE 
UPPER(city) NOT LIKE 'A%' 
AND UPPER(city) NOT LIKE 'E%' 
AND UPPER(city) NOT LIKE 'I%' 
AND UPPER(city) NOT LIKE 'O%' 
AND UPPER(city) NOT LIKE 'U%'; 

--EX7 name-of-employees
SELECT NAME FROM EMPLOYEE
ORDER BY NAME 
  
--EX8 salary-of-employees/
SELECT NAME FROM EMPLOYEE
WHERE SALARY > 2000 AND MONTHS <10

--EX9 
SELECT PRODUCT_ID FROM PRODUCTS
WHERE LOW_FATS = "Y" 
AND RECYCLABLE  ="Y"

--EX10
SELECT name FROM CUSTOMER
WHERE referee_id  IS NULL or referee_id = 1

--EX 11
SELECT NAME, POPULATION, AREA 
FROM WORLD
WHERE AREA >= 3000000 OR POPULATION >=25000000

--EX12
SELECT DISTINCT AUTHOR_ID AS id FROM VIEWS
WHERE VIEWER_ID = AUTHOR_ID
ORDER BY AUTHOR_ID

--EX13
SELECT part, assembly_step FROM parts_assembly
WHERE finish_date is NULL

--EX14
select * from lyft_drivers
where yearly_salary <= 30000 or yearly_salary >= 70000

--EX15
select advertising_channel from uber_advertising
WHERE money_spent > 100000 AND year =2019
