--EX1
SELECT NAME FROM CITY
WHERE POPULATION > 120000 AND COUNTRYCODE ="USA"

--EX2
SELECT * FROM CITY
WHERE COUNTRYCODE= "JPN"

--EX3

-- EX4
SELECT DISTINCT CITY FROM STATION
WHERE CITY LIKE 'A%' 
OR CITY LIKE 'E%' 
OR CITY LIKE 'I%' 
OR CITY LIKE 'O%' 
OR CITY LIKE 'U%'

--EX5
